lab4/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:film_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:film_id>/', views.cart_remove, name='cart_remove'),
]

lab4/feedbacks/urls.py
from django.urls import path

from .views import FeedbackListView, FeedbackCreateView, FeedbacksStatisticView

urlpatterns = [
    path("", FeedbackListView.as_view(), name="feedback-list"),
    path("create", FeedbackCreateView.as_view(), name="feedback-create"),
    path("statistics", FeedbacksStatisticView.as_view(), name="statistics"),
]

lab4/lab4/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

app_name = 'cinema'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include(('cinema.urls', 'cinema'), namespace='cinema')),
    path(
        "auth/",
        include(("users.urls", "users"), namespace="users"),
    ),
    path('news/', include('news.urls')),
    path("feedbacks/", include("feedbacks.urls")),
    path('info/', include('info.urls', namespace='info'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab4/feedbacks/models.py
import users.models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone


class Feedback(models.Model):
    title = models.CharField(max_length=255)
    rating = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    author = models.ForeignKey(
        users.models.CustomUser, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return f" {self.title} - {self.created_at}"

lab4/feedbacks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, TemplateView

from .models import Feedback


class FeedbackListView(ListView):
    template_name = "feedbacks/feedback-list.html"
    model = Feedback


class FeedbackCreateView(LoginRequiredMixin, CreateView):
    model = Feedback
    template_name = "feedbacks/feedback-create.html"
    fields = ("title", "rating", "content")
    success_url = reverse_lazy("feedback-list")
    login_url = reverse_lazy("users:signin")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class FeedbacksStatisticView(TemplateView):
    template_name = "feedbacks/statistics.html"

    def get(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return redirect(reverse("signin"))

        return super().get(request, args, kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        one = Feedback.objects.filter(rating=1)
        two = Feedback.objects.filter(rating=2)
        three = Feedback.objects.filter(rating=3)
        four = Feedback.objects.filter(rating=4)
        five = Feedback.objects.filter(rating=5)

        get_total_people = len(one) + len(two) + len(three) + len(four) + len(five)

        context["feedbacks"] = dict(
            one=one, two=two, three=three, four=four, five=five
        )
        context["one"] = len(one)
        context["two"] = len(two)
        context["three"] = len(three)
        context["four"] = len(four)
        context["five"] = len(five)
        return context

lab4/feedbacks/templates/feedbacks/feedback-create.html
{% extends 'cinema/base.html' %}

{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static '/css/feedbacks.css' %}">
{% endblock %}

{% block title %}Создание отзыва{% endblock %}

{% block content %}
    <div class="form-container">
        <h2>Создайте новый отзыв</h2>
        <form method="post">
            {% csrf_token %}
            <p>
                <label for="id_title">Заголовок:</label>
                <input type="text" name="title" maxlength="255" required="required" id="id_title">
            </p>
            <p>
                <label for="id_rating">Рейтинг:</label>
                <input type="number" name="rating" min="1" max="5" required="required" id="id_rating">
            </p>

            <p>
                <label for="id_content">Текст:</label>
                <textarea name="content" required="required" id="id_content"></textarea>
            </p>
            <button class="submit-button" type="submit">Сохранить</button>
        </form>
    </div>

{% endblock %}

lab4/feedbacks/templates/feedbacks/feedback-list.html
{% extends 'cinema/base.html' %}

{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static '/css/feedbacks.css' %}">
{% endblock %}

{% block title %}Отзывы{% endblock %}

{% block content %}
    <div class="feedback-page">
        <a class="button button-green" href="{% url 'feedback-create' %}">Новый отзыв</a>
        {% if user.is_staff %}
            <a href="{% url 'statistics' %}">Статистика</a>
        {% endif %}
        {% if not feedback_list %}
            <p>Нет отзывов</p>
        {% endif %}
        {% for feedback in object_list %}
            <article class="feedback" itemscope itemtype="https://schema.org/UserReview">
                <h2>
                    <span itemprop="name">{{ feedback.title }}</span> <span
                        itemprop="reviewRating">{{ feedback.rating }}</span>/5
                </h2>
                <h3>
                    Author: {{ feedback.author.first_name }} {{ feedback.author.last_name }} -
                    <time itemprop="dateCreated" content="{{ feedback.created_at }}">{{ feedback.created_at }}</time>
                </h3>
                <p itemprop="reviewBody">{{ feedback.content }}</p>
            </article>
        {% endfor %}
    </div>
{% endblock %}

lab4/feedbacks/templates/feedbacks/statistics.html
{% extends "cinema/base.html" %}

{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static '/css/feedbacks.css' %}">
{% endblock %}

{% block title %}Tours statistics{% endblock %}

{% block content %}
    <table>
        <caption>Статистика отзывов</caption>
        <thead>
        <tr>
            <th>Рейтинг</th>
            <th>Количество отзывов</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td><a href="{% url 'feedback-list' %}?rating=1">One</a></td>
            <td>{{ feedbacks.one|length }}</td>
        </tr>
        <tr>
            <td><a href="{% url 'feedback-list' %}?rating=2">Two</a></td>
            <td>{{ feedbacks.two|length }}</td>
        </tr>
        <tr>
            <td><a href="{% url 'feedback-list' %}?rating=3">Three</a></td>
            <td>{{ feedbacks.three|length }}</td>
        </tr>
        <tr>
            <td><a href="{% url 'feedback-list' %}?rating=4">Four</a></td>
            <td>{{ feedbacks.four|length }}</td>
        </tr>
        <tr>
            <td><a href="{% url 'feedback-list' %}?rating=5">Five</a></td>
            <td>{{ feedbacks.five|length }}</td>
        </tr>
        <tr>
            <td>kkjkj</td>
            <td></td>
        </tr>
        </tbody>
    </table>
{% endblock %}