lab4/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:film_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:film_id>/', views.cart_remove, name='cart_remove'),
]

lab4/cinema/urls.py
from django.urls import path

from . import views

app_name = 'cinema'

urlpatterns = [
    path('', views.main, name='main'),
    path('list', views.film_list, name='film_list'),
    path('<slug:category_slug>', views.film_list, name='film_list_by_category'),
    path('<int:id>/<slug:slug>', views.film_detail, name='film_detail'),
    path("<int:id>/<slug:slug>/edit", views.edit_film, name="film-edit"),
    path("list/create/session", views.create_session, name="session-create"),
    path("list/create/film", views.create_film, name="film-create"),
    path("<int:id>/<slug:slug>/delete", views.delete_film, name="film-delete"),
]

lab4/info/urls.py
from django.urls import path

from . import views

app_name = "info"
urlpatterns = [
    path('about_us', views.about_us, name='about_us'),
    path('faq', views.faq, name='faq'),
    path('privacy_policy', views.privacy_policy, name='privacy_policy'),
    path('contacts', views.contacts, name='contacts'),
    path('additional', views.additional, name='additional'),
    path('coupons', views.coupons, name='coupons.css'),
    path('vacancies', views.vacancies, name='vacancies')
]

lab4/lab4/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

app_name = 'cinema'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include(('cinema.urls', 'cinema'), namespace='cinema')),
    path(
        "auth/",
        include(("users.urls", "users"), namespace="users"),
    ),
    path('news/', include('news.urls')),
    path("feedbacks/", include("feedbacks.urls")),
    path('info/', include('info.urls', namespace='info'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab4/users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("signup/", views.RegistrationFormView.as_view(), name="signup"),
    path("signin/", views.SignInFormView.as_view(), name="signin"),
    path("logout/", views.LogoutFormView.as_view(), name="logout"),
]

lab4/cinema/models.py
import users.models
from django.db import models
from django.urls import reverse


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('cinema:film_list_by_category', args={self.slug})

    def __str__(self):
        return self.name


class Film(models.Model):
    category = models.ManyToManyField(Category, related_name='categories')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='films/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    duration = models.TimeField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        indexes = [
            models.Index(fields=['id', 'slug'])
        ]
        verbose_name = 'Фильм'
        verbose_name_plural = 'Фильмы'

    def get_absolute_url(self):
        return reverse('cinema:film_detail', args=[self.id, self.slug])

    def __str__(self):
        return self.name


class Hall(models.Model):
    capacity = models.IntegerField(default=0)
    seats_number = models.IntegerField()
    seats_row = models.IntegerField()
    hall_name = models.CharField(max_length=200)

    def __str__(self):
        return self.hall_name


class Session(models.Model):
    film = models.ForeignKey(Film, related_name='film', on_delete=models.CASCADE)
    hall = models.ForeignKey(Hall, related_name='hall', on_delete=models.DO_NOTHING)
    date = models.DateTimeField(null=True, blank=True)
    hall_name = models.CharField(max_length=200)
    price = models.IntegerField(default=0)

    class Meta:
        ordering = ('date', 'film')
        indexes = [
            models.Index(fields=['film'])
        ]
        verbose_name = 'Сеанс'
        verbose_name_plural = 'Сеансы'

    def get_absolute_url(self):
        return reverse('cinema:session', args=[self.id])

    def __str__(self):
        return f"Сессия {self.date}"


class Ticket(models.Model):
    user = models.ForeignKey(users.models.CustomUser, on_delete=models.DO_NOTHING, null=True)
    date_of_purchase = models.DateTimeField(auto_now_add=True)
    seat_number = models.PositiveIntegerField()
    seat_row = models.PositiveIntegerField()
    hall = models.ForeignKey(Hall, on_delete=models.DO_NOTHING)
    session = models.ForeignKey(Session, on_delete=models.DO_NOTHING)

    def __str__(self):
        return f"ticket {self.id}"

lab4/cinema/forms.py
from django import forms

from .models import Film, Session


class FilmForm(forms.ModelForm):
    class Meta:
        model = Film
        fields = ["category", "name", "slug", "image", "description", "duration"]


class SessionForm(forms.ModelForm):
    class Meta:
        model = Session
        fields = ["film", "hall", "date", "hall_name", "price"]

lab4/cinema/views.py
import json

from cart.forms import CartAddFilmForm
from django.db.models import Min
from django.shortcuts import render, get_object_or_404, redirect
from lab4.services import get_random_poem
from news.models import Article

from .forms import FilmForm, SessionForm
from .models import Category, Film, Session


def main(request):
    context = {}
    context["last_article"] = Article.objects.order_by("-created_at").first()
    context["poem"] = get_random_poem()
    return render(request, 'cinema/main.html', context)


# Create your views here.
def film_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    films = Session.objects.values('film').annotate(price=Min('price'))
    for film in films:
        film['film'] = Film.objects.get(id=film['film'])

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        answer = []
        for film in films:
            if category in film['film'].category.all():
                answer.append(film)
        films = answer

    js_list = []
    for film in films:
        js_list.append(film['price'])

    print(json.dumps(js_list))
    return render(request, 'cinema/film/list.html',
                  {'category': category,
                   'categories': categories,
                   'films': films,
                   'js_films': json.dumps(js_list)})


def film_detail(request, id, slug):
    film = get_object_or_404(Film, id=id)
    session = Session.objects.filter(film=film)
    cart_film_form = CartAddFilmForm()
    return render(request, 'cinema/film/detail.html',
                  {'film': film, 'cart_film_form': cart_film_form, 'sessions': session})


def edit_film(request, id, slug):
    film = get_object_or_404(Film, id=id)
    form = FilmForm(instance=film)
    if request.method == "POST":
        form = FilmForm(request.POST, instance=film)
        if form.is_valid():
            form.save()
            return redirect("/")
        else:
            form = FilmForm(instance=film)
    return render(request, "cinema/film/film_edit.html", {"form": form, "exhibit": film})


def create_session(request):
    form = SessionForm()
    if request.method == "POST":
        form = SessionForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("cinema:film_list")
        else:
            form = SessionForm()
    return render(request, "cinema/film/create_session.html", {"form": form})


def create_film(request):
    form = FilmForm()
    if request.method == "POST":
        form = FilmForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("cinema:session-create")
        else:
            form = FilmForm()
    return render(request, "cinema/film/create_film.html", {"form": form})


def delete_film(request, id, slug):
    film = get_object_or_404(Film, id=id)
    film.delete()
    return redirect("cinema:film_list")

lab4/cinema/templates/cinema/base.html
{% load static %}
<html lang="ru">
<head>
    <meta charset="utf-8"/>
    <meta name="keywords" content="Cinema, Ticket">
    <meta name="description" content="Cinema app"/>
    <meta name="author" content="Mikhail Dubinka"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>{% block title %}Кинотеатр{% endblock %}</title>
    <link type="image/png" sizes="96x96" rel="shortcut icon" href="{% static 'images/logo.png' %}"/>
    <link href="{% static '/css/base.css' %}" rel="stylesheet"/>
    {% block styles %}{% endblock %}
</head>
<body itemscope itemtype="https://schema.org/WebPage">
<section class="birthdate-prompt hidden" id="birthdate-prompt">
    <label for="date">Please, enter your birthdate</label>
    <input type="date" id="date"/>
    <button class="button button-green" id="birthdate-prompt-button">Submit</button>
</section>
<header id="header">
    <nav itemprop="breadcrumb">
        <a href="{% url 'cinema:main' %}" class="logo"></a>
        <a href="{% url 'cinema:film_list' %}">Каталог</a>
        <a href="{% url 'info:coupons.css' %}">Купоны</a>
        <a href="{% url 'news_page' %}">Новости</a>
        <a href="{% url 'feedback-list' %}">Отзывы</a>
        <a href="{% url 'info:about_us' %}">О нас</a>
        <a href="{% url 'info:faq' %}">FAQ</a>
        <a href="{% url 'info:contacts' %}">Контакты</a>
        <a href="{% url 'info:privacy_policy' %}">Политика приватности</a>
        <a href="{% url 'info:vacancies' %}">Вакансии</a>
        <a href="{% url 'info:additional' %}">Добавочное</a>
        {% if user.is_authenticated %}
            <a href="{% url 'users:logout' %}">Выйти</a>
        {% else %}
            <a href="{% url 'users:signin' %}">Войти</a>
        {% endif %}
        {% with total_items=cart|length %}
            {% if cart|length >= 0 %}
                <a class="cart_icon" href="{% url 'cart:cart_detail' %}">Корзина</a>
            {% endif %}
        {% endwith %}
    </nav>
</header>
<main id="content" itemprop="mainContentOfPage">
    <form>
        <label for="text-switch">Change text</label>
        <input type="checkbox" id="text-switch">
    </form>

    {% comment %}    <form id="settings-form">
        <fieldset>
            <legend>Settings</legend>
            <label>
                <button type="button" id="increase-font" style="width: 30px; height: 30px">+</button>
                <button type="button" id="decrease-font" style="width: 30px; height: 30px">-</button>
                Text size
            </label>
            <br>
            <label>
                <input type="color" id="text-color-picker">
                Text color
            </label>
        </fieldset>
    </form>{% endcomment %}
    {% block content %} {% endblock %}
</main>
<footer>
    {#    <aside> A joke for you: <strong>{{ joke }}</strong></aside>#}
    <p>Timer: <span id="timer"></span></p>
    <p>&copy; 2023 Cinema app. All rights reserved. </p>
</footer>
<script src="{% static 'js/timer.js' %}"></script>
<script src="{% static 'js/birthdatePrompt.js' %}"></script>
<script src="{% static 'js/textChanging.js' %}"></script>
{% block scripts %}
{% endblock %}
</body>
</html>

lab4/cinema/templates/cinema/main.html
{% extends 'cinema/base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static '/css/main-page.css' %}">
    <style>
        #banner {
            position: absolute;
            top: 250px;
            left: 100px;

            & img {
                width: 540px;
            }
        }
    </style>
{% endblock %}

{% block scripts %}
    <script src="{% static '/js/banners.js' %}"></script>
{% endblock %}

{% block title %}Главная страница{% endblock %}

{% block content %}
    <section id="recent-article">
        <h2>Последняя новость</h2>
        <h3 itemscope itemtype="https://schema.org/Article">
            <a itemprop="name" href="{{ last_article.get_absolute_url }}">{{ last_article.title }}</a> -
            <time itemprop="dateCreated"
                  content="{{ last_article.created_at }}">{{ last_article.created_at|date:'Y-m-d H:i' }}</time>
        </h3>
        <p>{{ last_article.description }}</p>
    </section>

    <figure>
        <img class="jump" src="{% static 'images/cinema.webp' %}" alt="Cinema building">
        <figcaption>
            <em>Познакомьтесь c искусством через наш кинотеатр.</em>
        </figcaption>
    </figure>
    <section id="banner">
        <a id="banner-link">
            <img src='https://images.wallpaperscraft.ru/image/single/kot_sneg_vzgliad_95615_1920x1080.jpg'
                 alt="banner" id="banner-img">
        </a>
        {% if user.is_staff %}
            <form id="interval-form">
                <label for="interval">Enter interval in ms: </label>
                <input type="number" name="interval" min="10" id="interval">
                <input type="submit">
            </form>
        {% endif %}
    </section>
    <section class="poem">
        {% for line in poem %}
            <p>{{ line }}</p>
        {% endfor %}
    </section>
    <section>
        <h2>Наши партнеры:</h2>
        <ul class="company-list">
            <li class="company" itemscope itemtype="https://schema.org/Organization">
                <meta itemprop="url" content="https://www.apple.com/">
                <a href="https://www.apple.com/" itemprop="name">Apple</a>
                <img itemprop="image" src="https://makingteams.com/wp-content/uploads/2021/04/Apple.png"
                     alt="apple icon">
            </li>
            <li class="company" itemscope itemtype="https://schema.org/Organization">
                <meta itemprop="url" content="https://bsuir.by">
                <a href="https://bsuir.by" itemprop="name">Bsuir</a>
                <img itemprop="image" src="https://iis.bsuir.by/static/media/logo.5683d3b9.svg" alt="bsuir icon">
            </li>
        </ul>
    </section>
{% endblock %}