lab4/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:film_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:film_id>/', views.cart_remove, name='cart_remove'),
]

lab4/cinema/urls.py
from django.urls import path

from . import views

app_name = 'cinema'

urlpatterns = [
    path('', views.main, name='main'),
    path('list', views.film_list, name='film_list'),
    path('<slug:category_slug>', views.film_list, name='film_list_by_category'),
    path('<int:id>/<slug:slug>', views.film_detail, name='film_detail'),
    path("<int:id>/<slug:slug>/edit", views.edit_film, name="film-edit"),
    path("list/create/session", views.create_session, name="session-create"),
    path("list/create/film", views.create_film, name="film-create"),
    path("<int:id>/<slug:slug>/delete", views.delete_film, name="film-delete"),
]

lab4/lab4/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

app_name = 'cinema'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include(('cinema.urls', 'cinema'), namespace='cinema')),
    path(
        "auth/",
        include(("users.urls", "users"), namespace="users"),
    ),
    path('news/', include('news.urls')),
    path("feedbacks/", include("feedbacks.urls")),
    path('info/', include('info.urls', namespace='info'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab4/cinema/models.py
import users.models
from django.db import models
from django.urls import reverse


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('cinema:film_list_by_category', args={self.slug})

    def __str__(self):
        return self.name


class Film(models.Model):
    category = models.ManyToManyField(Category, related_name='categories')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='films/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    duration = models.TimeField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        indexes = [
            models.Index(fields=['id', 'slug'])
        ]
        verbose_name = 'Фильм'
        verbose_name_plural = 'Фильмы'

    def get_absolute_url(self):
        return reverse('cinema:film_detail', args=[self.id, self.slug])

    def __str__(self):
        return self.name


class Hall(models.Model):
    capacity = models.IntegerField(default=0)
    seats_number = models.IntegerField()
    seats_row = models.IntegerField()
    hall_name = models.CharField(max_length=200)

    def __str__(self):
        return self.hall_name


class Session(models.Model):
    film = models.ForeignKey(Film, related_name='film', on_delete=models.CASCADE)
    hall = models.ForeignKey(Hall, related_name='hall', on_delete=models.DO_NOTHING)
    date = models.DateTimeField(null=True, blank=True)
    hall_name = models.CharField(max_length=200)
    price = models.IntegerField(default=0)

    class Meta:
        ordering = ('date', 'film')
        indexes = [
            models.Index(fields=['film'])
        ]
        verbose_name = 'Сеанс'
        verbose_name_plural = 'Сеансы'

    def get_absolute_url(self):
        return reverse('cinema:session', args=[self.id])

    def __str__(self):
        return f"Сессия {self.date}"


class Ticket(models.Model):
    user = models.ForeignKey(users.models.CustomUser, on_delete=models.DO_NOTHING, null=True)
    date_of_purchase = models.DateTimeField(auto_now_add=True)
    seat_number = models.PositiveIntegerField()
    seat_row = models.PositiveIntegerField()
    hall = models.ForeignKey(Hall, on_delete=models.DO_NOTHING)
    session = models.ForeignKey(Session, on_delete=models.DO_NOTHING)

    def __str__(self):
        return f"ticket {self.id}"

lab4/cinema/forms.py
from django import forms

from .models import Film, Session


class FilmForm(forms.ModelForm):
    class Meta:
        model = Film
        fields = ["category", "name", "slug", "image", "description", "duration"]


class SessionForm(forms.ModelForm):
    class Meta:
        model = Session
        fields = ["film", "hall", "date", "hall_name", "price"]

lab4/cinema/views.py
import json

from cart.forms import CartAddFilmForm
from django.db.models import Min
from django.shortcuts import render, get_object_or_404, redirect
from lab4.services import get_random_poem
from news.models import Article

from .forms import FilmForm, SessionForm
from .models import Category, Film, Session


def main(request):
    context = {}
    context["last_article"] = Article.objects.order_by("-created_at").first()
    context["poem"] = get_random_poem()
    return render(request, 'cinema/main.html', context)


# Create your views here.
def film_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    films = Session.objects.values('film').annotate(price=Min('price'))
    for film in films:
        film['film'] = Film.objects.get(id=film['film'])

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        answer = []
        for film in films:
            if category in film['film'].category.all():
                answer.append(film)
        films = answer

    js_list = []
    for film in films:
        js_list.append(film['price'])

    print(json.dumps(js_list))
    return render(request, 'cinema/film/list.html',
                  {'category': category,
                   'categories': categories,
                   'films': films,
                   'js_films': json.dumps(js_list)})


def film_detail(request, id, slug):
    film = get_object_or_404(Film, id=id)
    session = Session.objects.filter(film=film)
    cart_film_form = CartAddFilmForm()
    return render(request, 'cinema/film/detail.html',
                  {'film': film, 'cart_film_form': cart_film_form, 'sessions': session})


def edit_film(request, id, slug):
    film = get_object_or_404(Film, id=id)
    form = FilmForm(instance=film)
    if request.method == "POST":
        form = FilmForm(request.POST, instance=film)
        if form.is_valid():
            form.save()
            return redirect("/")
        else:
            form = FilmForm(instance=film)
    return render(request, "cinema/film/film_edit.html", {"form": form, "exhibit": film})


def create_session(request):
    form = SessionForm()
    if request.method == "POST":
        form = SessionForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("cinema:film_list")
        else:
            form = SessionForm()
    return render(request, "cinema/film/create_session.html", {"form": form})


def create_film(request):
    form = FilmForm()
    if request.method == "POST":
        form = FilmForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("cinema:session-create")
        else:
            form = FilmForm()
    return render(request, "cinema/film/create_film.html", {"form": form})


def delete_film(request, id, slug):
    film = get_object_or_404(Film, id=id)
    film.delete()
    return redirect("cinema:film_list")

lab4/cinema/templates/cinema/film/create_film.html
{% extends "cinema/base.html" %}

{% block title %}Создание фильма{% endblock %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

lab4/cinema/templates/cinema/film/create_session.html
{% extends "cinema/base.html" %}

{% block title %}Создание сессии{% endblock %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
    <p><a href="{% url 'cinema:film-create' %}">Create film</a></p>
{% endblock %}

lab4/cinema/templates/cinema/film/detail.html
{% extends "cinema/base.html" %}
{% load static %}
{% block title %}
    {{ film.name }}
{% endblock %}
{% block content %}

    <link href="{% static '/css/detail.css' %}" rel="stylesheet">
    <div class="product-detail">
        <div class="image-container">
            <img src="{% if film.image %}{{ film.image.url }}{% else %}{% static 'images/img.png' %}{% endif %}">
            <h1>{{ film.name }}</h1>
            <div class="cart-description">{{ product.description|linebreaks }}</div>
        </div>
        <h2>{% for category in film.category.all %}{{ category }} {% endfor %}</h2>
        <p class="weight">{{ film.description }}</p>
    </div>
    {#    <p class="price">{{ film.price }} руб.</p>#}
    <form action="{% url 'cart:cart_add' film.id %}" method="post">
        {% csrf_token %}
        <label class="count-label">Количество: </label>
        {{ cart_film_form.quantity }}
        <input class="submit-button" type="submit" value="Добавить в корзину">
    </form>
    {% if user.is_staff %}
        <a href="{% url 'cinema:film-edit' film.id film.slug %}">Edit</a> |
        <a href="{% url 'cinema:film-delete' film.id film.slug %}">Delete</a>
    {% endif %}
{% endblock %}

lab4/cinema/templates/cinema/film/film_edit.html
{% extends "cinema/base.html" %}

{% block title %}Изменить фильм{% endblock %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

lab4/cinema/templates/cinema/film/list.html
{% extends "cinema/base.html" %}
{% load static %}
{% block styles %}
    <link href="{% static '/css/list.css' %}" rel="stylesheet">
    <style>

        .fade-out {
            opacity: 0;
            filter: blur(5px);
        {#transform: translateX(-100%);#} transition: all 1s;
        }

        .fade-in {
            opacity: 1;
            filter: blur(0);
        {#transform: translateX(0);#}
        }

        .crossed {
            text-decoration: line-through;
        }
    </style>
{% endblock %}

{% block scripts %}
    <div id="my-element" data-context="{{ js_films }}"></div>
    <script src="{% static 'js/scrollAnimation.js' %}"></script>
    <script src="{% static 'js/coupons.js' %}"></script>
{% endblock %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Кинотеатр{% endif %}
{% endblock %}
{% block content %}
    <div class="sidebar">
        <ul class="sidebar_categories">
            <li {% if not category %}class="selected category"{% else %}class="category"{% endif %}>
                <a class="category_link" href="{% url 'cinema:film_list' %}">Все</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected category"{% else %}class="category"{% endif %}>
                    <a class="category_link" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <h1>{% if category %}{{ category.name }}{% else %}Все{% endif %}</h1>
    {% if user.is_staff %}
        <p><a href="{% url 'cinema:session-create' %}">Create</a></p>
    {% endif %}
    <form id="coupon-form">
        <label for="coupon-input">Enter coupon</label>
        <input type="text" id="coupon-input">
        <input type="submit">
    </form>
    <p id="coupon-form-text"></p>
    <div class="film-list">
        {% for item in films %}
            {% with film=item.film %}
                <article class="film">
                    <img class="animation" src="
                            {% if film.image %}{{ film.image.url }}{% else %}{% static 'images/img.png' %}{% endif %}">
                    <div class="name">{{ film.name }}</div>
                    <div class="description">{{ film.description }}</div>
                    <div class="order">
                        <p>от <span class="price">{{ item.price }}</span><span class="new-price"></span> руб.</p>
                        <a class="order-button" href="{{ film.get_absolute_url }}">Билет</a>
                    </div>
                </article>
            {% endwith %}
        {% endfor %}
    </div>
{% endblock %}